version: '2'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    - "3001:3001"
    networks:
    - backend
    command:
      npm run start
    depends_on:
    - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    networks:
    - backend
    command:
      node index.js
    depends_on:
    - neo4j
    - elasticsearch
    - nginx
    - redis
  neo4j:
    image: neo4j
    ports:
    - "7474:7474"
    - "7687:7687"
    volumes:
    - ./neo4j/data:/data
    - ./neo4j/conf/scripts:/conf
    networks:
    - backend
  elasticsearch:
    image: elasticsearch
    command: elasticsearch -Des.network.bind_host=0.0.0.0
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - ./elasticsearch/data:/usr/share/elasticsearch/data
    - ./elasticsearch/config/scripts:/usr/share/elasticsearch/config
    networks:
    - backend
  nginx:
    image: nginx
    ports:
    - "80:80"
    volumes:
    - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
    - backend
  redis:
    image: redis
    ports:
    - "6379:6379"
    volumes:
    - ./redis/data:/data
    networks:
    - backend
networks:
  backend:
